#APPLICATION BROWSER
browser=chrome
#APPLICATION URL
url=https://www.naukri.com/nlogin/login
#APPLICATION USERNAME AND PASSWORD
username=
password=
excelpath=C:\\Users\\ASUS\\IdeaProjects\\NaukriProject\\src\\test\\resources\\Excel.xlsx
start=C:\\Users\ASUS\\IdeaProjects\\NaukriProject\\Reports
end=C:\\Users\\ASUS\\IdeaProjects\\NaukriProject\\Reports\\index.html

